apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/azimbabu/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
  - name: order-service
    newName: ghcr.io/azimbabu/order-service
    newTag: ecb6a12e41b4386efcc20d66a514d99f272b78a2

replicas:
- count: 1
  name: order-service
